dist: xenial
language: go
sudo: required

go:
  - 1.x

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libhdf5-serial-dev python3-venv

script:
  - python3 --version
  - ./build/bootstrap-test-env.sh
  - ls -a
  - go test -v ./...
  - ./build/build.sh
  - ./build/run_test.sh
  - ls -a


